const comunas = [
    {
      label: 'Región de Arica y Parinacota',
      options: [
        { label: 'Arica', value: 'Arica', region: 'Región de Arica y Parinacota' },
        { label: 'Camarones', value: 'Camarones', region: 'Región de Arica y Parinacota' },
        { label: 'General Lagos', value: 'General Lagos', region: 'Región de Arica y Parinacota' },
        { label: 'Putre', value: 'Putre', region: 'Región de Arica y Parinacota' },
      ]
    },
    {
      label: 'Región de Tarapacá',
      options: [
        { label: 'Alto Hospicio', value: 'Alto Hospicio', region: 'Región de Tarapacá' },
        { label: 'Camiña', value: 'Camiña', region: 'Región de Tarapacá' },
        { label: 'Colchane', value: 'Colchane', region: 'Región de Tarapacá' },
        { label: 'Huara', value: 'Huara', region: 'Región de Tarapacá' },
        { label: 'Iquique', value: 'Iquique', region: 'Región de Tarapacá' },
        { label: 'Pica', value: 'Pica', region: 'Región de Tarapacá' },
        { label: 'Pozo Almonte', value: 'Pozo Almonte', region: 'Región de Tarapacá' },
      ]
    },
    {
      label: 'Región de Antofagasta',
      options: [
        { label: 'Antofagasta', value: 'Antofagasta', region: 'Región de Antofagasta' },
        { label: 'Calama', value: 'Calama', region: 'Región de Antofagasta' },
        { label: 'María Elena', value: 'María Elena', region: 'Región de Antofagasta' },
        { label: 'Mejillones', value: 'Mejillones', region: 'Región de Antofagasta' },
        { label: 'Ollagüe', value: 'Ollagüe', region: 'Región de Antofagasta' },
        { label: 'San Pedro de Atacama', value: 'San Pedro de Atacama', region: 'Región de Antofagasta' },
        { label: 'Sierra Gorda', value: 'Sierra Gorda', region: 'Región de Antofagasta' },
        { label: 'Taltal', value: 'Taltal', region: 'Región de Antofagasta' },
        { label: 'Tocopilla', value: 'Tocopilla', region: 'Región de Antofagasta' },
      ]
    },
    {
        label: 'Región de Atacama',
        options: [
            { label: 'Alto del Carmen', value: 'Alto del Carmen', region: 'Región de Atacama' },
            { label: 'Caldera', value: 'Caldera', region: 'Región de Atacama' },
            { label: 'Chañaral', value: 'Chañaral', region: 'Región de Atacama' },
            { label: 'Copiapó', value: 'Copiapó', region: 'Región de Atacama' },
            { label: 'Diego de Almagro', value: 'Diego de Almagro', region: 'Región de Atacama' },
            { label: 'Freirina', value: 'Freirina', region: 'Región de Atacama' },
            { label: 'Huasco', value: 'Huasco', region: 'Región de Atacama' },
            { label: 'Tierra Amarilla', value: 'Tierra Amarilla', region: 'Región de Atacama' },
            { label: 'Vallenar', value: 'Vallenar', region: 'Región de Atacama' },
        ]
      },
      {
        label: 'Región de Coquimbo',
        options: [
            { label: 'Andacollo', value: 'Andacollo', region: 'Región de Coquimbo' },
            { label: 'Canela', value: 'Canela', region: 'Región de Coquimbo' },
            { label: 'Combarbalá', value: 'Combarbalá', region: 'Región de Coquimbo' },
            { label: 'Coquimbo', value: 'Coquimbo', region: 'Región de Coquimbo' },
            { label: 'Illapel', value: 'Illapel', region: 'Región de Coquimbo' },
            { label: 'La Higuera', value: 'La Higuera', region: 'Región de Coquimbo' },
            { label: 'La Serena', value: 'La Serena', region: 'Región de Coquimbo' },
            { label: 'Los Vilos', value: 'Los Vilos', region: 'Región de Coquimbo' },
            { label: 'Monte Patria', value: 'Monte Patria', region: 'Región de Coquimbo' },
          { label: 'Ovalle', value: 'Ovalle', region: 'Región de Coquimbo' },
          { label: 'Paihuano', value: 'Paihuano', region: 'Región de Coquimbo' },
          { label: 'Punitaqui', value: 'Punitaqui', region: 'Región de Coquimbo' },
          { label: 'Río Hurtado', value: 'Río Hurtado', region: 'Región de Coquimbo' },
          { label: 'Salamanca', value: 'Salamanca', region: 'Región de Coquimbo' },
          { label: 'Vicuña', value: 'Vicuña', region: 'Región de Coquimbo' },
        ]
      },
      {
        label: 'Región de Valparaíso',
        options: [
          { label: 'Algarrobo', value: 'Algarrobo', region: 'Región de Valparaíso' },
          { label: 'Cabildo', value: 'Cabildo', region: 'Región de Valparaíso' },
          { label: 'Calera', value: 'Calera', region: 'Región de Valparaíso' },
          { label: 'Calle Larga', value: 'Calle Larga', region: 'Región de Valparaíso' },
          { label: 'Cartagena', value: 'Cartagena', region: 'Región de Valparaíso' },
            { label: 'Casablanca', value: 'Casablanca', region: 'Región de Valparaíso' },
            { label: 'Catemu', value: 'Catemu', region: 'Región de Valparaíso' },
            { label: 'Concón', value: 'Concón', region: 'Región de Valparaíso' },
            { label: 'El Quisco', value: 'El Quisco', region: 'Región de Valparaíso' },
            { label: 'El Tabo', value: 'El Tabo', region: 'Región de Valparaíso' },
            { label: 'Hijuelas', value: 'Hijuelas' },
            { label: 'Isla de Pascua', value: 'Isla de Pascua', region: 'Región de Valparaíso' },
            { label: 'Juan Fernández', value: 'Juan Fernández', region: 'Región de Valparaíso' },
          { label: 'La Cruz', value: 'La Cruz', region: 'Región de Valparaíso' },
          { label: 'La Ligua', value: 'La Ligua', region: 'Región de Valparaíso' },
          { label: 'Limache', value: 'Limache', region: 'Región de Valparaíso' },
          { label: 'Llaillay', value: 'Llaillay', region: 'Región de Valparaíso' },
          { label: 'Los Andes', value: 'Los Andes', region: 'Región de Valparaíso' },
          { label: 'Nogales', value: 'Nogales', region: 'Región de Valparaíso' },
          { label: 'Olmué', value: 'Olmué', region: 'Región de Valparaíso' },
          { label: 'Panquehue', value: 'Panquehue', region: 'Región de Valparaíso' },
          { label: 'Papudo', value: 'Papudo', region: 'Región de Valparaíso' },
          { label: 'Petorca', value: 'Petorca', region: 'Región de Valparaíso' },
          { label: 'Puchuncaví', value: 'Puchuncaví', region: 'Región de Valparaíso' },
          { label: 'Putaendo', value: 'Putaendo', region: 'Región de Valparaíso' },
          { label: 'Quillota', value: 'Quillota', region: 'Región de Valparaíso' },
            { label: 'Quilpué', value: 'Quilpué', region: 'Región de Valparaíso' },
            { label: 'Quintero', value: 'Quintero', region: 'Región de Valparaíso' },
            { label: 'Rinconada', value: 'Rinconada', region: 'Región de Valparaíso' },
            { label: 'San Antonio', value: 'San Antonio', region: 'Región de Valparaíso' },
            { label: 'San Esteban', value: 'San Esteban', region: 'Región de Valparaíso' },
            { label: 'San Felipe', value: 'San Felipe', region: 'Región de Valparaíso' },
            { label: 'Santa María', value: 'Santa María', region: 'Región de Valparaíso' },
            { label: 'Santo Domingo', value: 'Santo Domingo', region: 'Región de Valparaíso' },
          { label: 'Valparaíso', value: 'Valparaíso', region: 'Región de Valparaíso' },
          { label: 'Villa Alemana', value: 'Villa Alemana', region: 'Región de Valparaíso' },
          { label: 'Viña del Mar', value: 'Viña del Mar', region: 'Región de Valparaíso' },
          { label: 'Zapallar', value: 'Zapallar', region: 'Región de Valparaíso' },
        ]
      },
      {
        label: "Región del Libertador General Bernardo O'Higgins",
        options: [
          { label: 'Chépica', value: 'Chépica', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Chimbarongo', value: 'Chimbarongo', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Codegua', value: 'Codegua', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Coínco', value: 'Coínco', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Coltauco', value: 'Coltauco', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Doñihue', value: 'Doñihue', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Graneros', value: 'Graneros', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'La Estrella', value: 'La Estrella', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Las Cabras', value: 'Las Cabras', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Litueche', value: 'Litueche', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Lolol', value: 'Lolol', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Machalí', value: 'Machalí', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Malloa', value: 'Malloa', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Marchihue', value: 'Marchihue', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Mostazal', value: 'Mostazal', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Nancagua', value: 'Nancagua', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Navidad', value: 'Navidad', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Olivar', value: 'Olivar', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Palmilla', value: 'Palmilla', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Paredones', value: 'Paredones', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Peralillo', value: 'Peralillo', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Peumo', value: 'Peumo', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Pichidegua', value: 'Pichidegua', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Pichilemu', value: 'Pichilemu', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Placilla', value: 'Placilla', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Pumanque', value: 'Pumanque', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Quinta de Tilcoco', value: 'Quinta de Tilcoco', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Rancagua', value: 'Rancagua', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Rengo', value: 'Rengo', region: "Región del Libertador General Bernardo O'Higgins" },
          { label: 'Requínoa', value: 'Requínoa', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'San Fernando', value: 'San Fernando', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'Santa Cruz', value: 'Santa Cruz', region: "Región del Libertador General Bernardo O'Higgins" },
            { label: 'San Vicente', value: 'San Vicente', region: "Región del Libertador General Bernardo O'Higgins" },
        ]
      },
      {
        label: 'Región del Maule',
        options: [
          { label: 'Cauquenes', value: 'Cauquenes', region: 'Región del Maule' },
          { label: 'Chanco', value: 'Chanco', region: 'Región del Maule' },
          { label: 'Colbún', value: 'Colbún', region: 'Región del Maule' },
          { label: 'Constitución', value: 'Constitución', region: 'Región del Maule' },
          { label: 'Curepto', value: 'Curepto', region: 'Región del Maule' },
          { label: 'Curicó', value: 'Curicó', region: 'Región del Maule' },
          { label: 'Empedrado', value: 'Empedrado', region: 'Región del Maule' },
          { label: 'Hualañé', value: 'Hualañé', region: 'Región del Maule' },
          { label: 'Licantén', value: 'Licantén', region: 'Región del Maule' },
          { label: 'Linares', value: 'Linares', region: 'Región del Maule' },
          { label: 'Longaví', value: 'Longaví', region: 'Región del Maule' },
          { label: 'Maule', value: 'Maule', region: 'Región del Maule' },
          { label: 'Molina', value: 'Molina', region: 'Región del Maule' },
            { label: 'Parral', value: 'Parral', region: 'Región del Maule' },
            { label: 'Pelarco', value: 'Pelarco', region: 'Región del Maule' },
            { label: 'Pelluhue', value: 'Pelluhue', region: 'Región del Maule' },
            { label: 'Pencahue', value: 'Pencahue', region: 'Región del Maule' },
            { label: 'Rauco', value: 'Rauco', region: 'Región del Maule' },
            { label: 'Retiro', value: 'Retiro', region: 'Región del Maule' },
            { label: 'Río Claro', value: 'Río Claro', region: 'Región del Maule' },
            { label: 'Romeral', value: 'Romeral', region: 'Región del Maule' },
          { label: 'Sagrada Familia', value: 'Sagrada Familia', region: 'Región del Maule' },
          { label: 'San Clemente', value: 'San Clemente', region: 'Región del Maule' },
          { label: 'San Javier', value: 'San Javier', region: 'Región del Maule' },
          { label: 'San Rafael', value: 'San Rafael', region: 'Región del Maule' },
          { label: 'Talca', value: 'Talca', region: 'Región del Maule' },
          { label: 'Teno', value: 'Teno', region: 'Región del Maule' },
          { label: 'Vichuquén', value: 'Vichuquén', region: 'Región del Maule' },
          { label: 'Villa Alegre', value: 'Villa Alegre', region: 'Región del Maule' },
          { label: 'Yerbas Buenas', value: 'Yerbas Buenas', region: 'Región del Maule' },
        ]
      },
      {
        label: 'Región de Ñuble',
        options: [
            { label: 'Bulnes', value: 'Bulnes', region: 'Región de Ñuble' },
            { label: 'Chillán', value: 'Chillán', region: 'Región de Ñuble' },
            { label: 'Chillán Viejo', value: 'Chillán Viejo', region: 'Región de Ñuble' },
            { label: 'Cobquecura', value: 'Cobquecura', region: 'Región de Ñuble' },
            { label: 'Coelemu', value: 'Coelemu', region: 'Región de Ñuble' },
            { label: 'Coihueco', value: 'Coihueco', region: 'Región de Ñuble' },
            { label: 'El Carmen', value: 'El Carmen', region: 'Región de Ñuble' },
            { label: 'Ninhue', value: 'Ninhue', region: 'Región de Ñuble' },
            { label: 'Ñiquén', value: 'Ñiquén', region: 'Región de Ñuble' },
            { label: 'Pemuco', value: 'Pemuco', region: 'Región de Ñuble' },
            { label: 'Pinto', value: 'Pinto', region: 'Región de Ñuble' },
            { label: 'Portezuelo', value: 'Portezuelo', region: 'Región de Ñuble' },
            { label: 'Quillón', value: 'Quillón', region: 'Región de Ñuble' },
              { label: 'Quirihue', value: 'Quirihue', region: 'Región de Ñuble' },
              { label: 'Ránquil', value: 'Ránquil', region: 'Región de Ñuble' },
              { label: 'San Carlos', value: 'San Carlos', region: 'Región de Ñuble' },
              { label: 'San Fabián', value: 'San Fabián', region: 'Región de Ñuble' },
              { label: 'San Ignacio', value: 'San Ignacio', region: 'Región de Ñuble' },
              { label: 'San Nicolás', value: 'San Nicolás', region: 'Región de Ñuble' },
              { label: 'Treguaco', value: 'Treguaco', region: 'Región de Ñuble' },
              { label: 'Yungay', value: 'Yungay', region: 'Región de Ñuble' },
        ]
      },
      {
        label: 'Región del Biobío',
        options: [
          { label: 'Alto Biobío', value: 'Alto Biobío', region: 'Región del Biobío' },
          { label: 'Antuco', value: 'Antuco', region: 'Región del Biobío' },
          { label: 'Arauco', value: 'Arauco', region: 'Región del Biobío' },
          { label: 'Cabrero', value: 'Cabrero', region: 'Región del Biobío' },
          { label: 'Cañete', value: 'Cañete', region: 'Región del Biobío' },
          { label: 'Chiguayante', value: 'Chiguayante', region: 'Región del Biobío' },
          { label: 'Concepción', value: 'Concepción', region: 'Región del Biobío' },
          { label: 'Contulmo', value: 'Contulmo', region: 'Región del Biobío' },
          { label: 'Coronel', value: 'Coronel', region: 'Región del Biobío' },
            { label: 'Curanilahue', value: 'Curanilahue', region: 'Región del Biobío' },
            { label: 'Florida', value: 'Florida', region: 'Región del Biobío' },
            { label: 'Hualpén', value: 'Hualpén', region: 'Región del Biobío' },
            { label: 'Hualqui', value: 'Hualqui', region: 'Región del Biobío' },
            { label: 'Laja', value: 'Laja', region: 'Región del Biobío' },
            { label: 'Lebu', value: 'Lebu', region: 'Región del Biobío' },
            { label: 'Los Alamos', value: 'Los Alamos', region: 'Región del Biobío' },
            { label: 'Los Angeles', value: 'Los Angeles', region: 'Región del Biobío' },
          { label: 'Lota', value: 'Lota', region: 'Región del Biobío' },
          { label: 'Mulchén', value: 'Mulchén', region: 'Región del Biobío' },
          { label: 'Nacimiento', value: 'Nacimiento', region: 'Región del Biobío' },
          { label: 'Negrete', value: 'Negrete', region: 'Región del Biobío' },
          { label: 'Penco', value: 'Penco', region: 'Región del Biobío' },
          { label: 'Quilaco', value: 'Quilaco', region: 'Región del Biobío' },
          { label: 'Quilleco', value: 'Quilleco', region: 'Región del Biobío' },
          { label: 'San Pedro de la Paz', value: 'San Pedro de la Paz', region: 'Región del Biobío' },
          { label: 'San Rosendo', value: 'San Rosendo', region: 'Región del Biobío' },
          { label: 'Santa Bárbara', value: 'Santa Bárbara', region: 'Región del Biobío' },
          { label: 'Santa Juana', value: 'Santa Juana', region: 'Región del Biobío' },
          { label: 'Talcahuano', value: 'Talcahuano', region: 'Región del Biobío' },
          { label: 'Tirúa', value: 'Tirúa', region: 'Región del Biobío' },
            { label: 'Tomé', value: 'Tomé', region: 'Región del Biobío' },
            { label: 'Tucapel', value: 'Tucapel', region: 'Región del Biobío' },
            { label: 'Yumbel', value: 'Yumbel', region: 'Región del Biobío' },
        ]
      },
      {
        label: 'Región de La Araucanía',
        options: [
            { label: 'Angol', value: 'Angol', region: 'Región de La Araucanía' },
            { label: 'Carahue', value: 'Carahue', region: 'Región de La Araucanía' },
            { label: 'Cholchol', value: 'Cholchol', region: 'Región de La Araucanía' },
            { label: 'Collipulli', value: 'Collipulli', region: 'Región de La Araucanía' },
            { label: 'Cunco', value: 'Cunco', region: 'Región de La Araucanía' },
            { label: 'Curacautín', value: 'Curacautín', region: 'Región de La Araucanía' },
            { label: 'Curarrehue', value: 'Curarrehue', region: 'Región de La Araucanía' },
            { label: 'Ercilla', value: 'Ercilla', region: 'Región de La Araucanía' },
            { label: 'Freire', value: 'Freire', region: 'Región de La Araucanía' },
              { label: 'Galvarino', value: 'Galvarino', region: 'Región de La Araucanía' },
              { label: 'Gorbea', value: 'Gorbea', region: 'Región de La Araucanía' },
              { label: 'Lautaro', value: 'Lautaro', region: 'Región de La Araucanía' },
              { label: 'Loncoche', value: 'Loncoche', region: 'Región de La Araucanía' },
              { label: 'Lonquimay', value: 'Lonquimay', region: 'Región de La Araucanía' },
              { label: 'Los Sauces', value: 'Los Sauces', region: 'Región de La Araucanía' },
              { label: 'Lumaco', value: 'Lumaco', region: 'Región de La Araucanía' },
              { label: 'Melipeuco', value: 'Melipeuco', region: 'Región de La Araucanía' },
            { label: 'Nueva Imperial', value: 'Nueva Imperial', region: 'Región de La Araucanía' },
            { label: 'Padre Las Casas', value: 'Padre Las Casas', region: 'Región de La Araucanía' },
            { label: 'Perquenco', value: 'Perquenco', region: 'Región de La Araucanía' },
            { label: 'Pitrufquén', value: 'Pitrufquén', region: 'Región de La Araucanía' },
            { label: 'Pucón', value: 'Pucón', region: 'Región de La Araucanía' },
            { label: 'Purén', value: 'Purén', region: 'Región de La Araucanía' },
            { label: 'Renaico', value: 'Renaico', region: 'Región de La Araucanía' },
            { label: 'Saavedra', value: 'Saavedra', region: 'Región de La Araucanía' },
            { label: 'Temuco', value: 'Temuco', region: 'Región de La Araucanía' },
            { label: 'Teodoro Schmidt', value: 'Teodoro Schmidt', region: 'Región de La Araucanía' },
            { label: 'Toltén', value: 'Toltén', region: 'Región de La Araucanía' },
            { label: 'Traiguén', value: 'Traiguén', region: 'Región de La Araucanía' },
            { label: 'Victoria', value: 'Victoria', region: 'Región de La Araucanía' },
              { label: 'Vilcún', value: 'Vilcún', region: 'Región de La Araucanía' },
              { label: 'Villarrica', value: 'Villarrica', region: 'Región de La Araucanía' },
        ]
      },
      {
        label: 'Región de Los Ríos',
        options: [
          { label: 'Corral', value: 'Corral', region: 'Región de Los Ríos' },
          { label: 'Futrono', value: 'Futrono', region: 'Región de Los Ríos' },
          { label: 'Lago Ranco', value: 'Lago Ranco', region: 'Región de Los Ríos' },
          { label: 'Lanco', value: 'Lanco', region: 'Región de Los Ríos' },
          { label: 'La Unión', value: 'La Unión', region: 'Región de Los Ríos' },
          { label: 'Los Lagos', value: 'Los Lagos', region: 'Región de Los Ríos' },
          { label: 'Máfil', value: 'Máfil', region: 'Región de Los Ríos' },
          { label: 'Mariquina', value: 'Mariquina', region: 'Región de Los Ríos' },
          { label: 'Paillaco', value: 'Paillaco', region: 'Región de Los Ríos' },
          { label: 'Panguipulli', value: 'Panguipulli', region: 'Región de Los Ríos' },
          { label: 'Río Bueno', value: 'Río Bueno', region: 'Región de Los Ríos' },
          { label: 'Valdivia', value: 'Valdivia', region: 'Región de Los Ríos' },
        ]
      },
      {
        label: 'Región de Los Lagos',
        options: [
          { label: 'Ancud', value: 'Ancud', region: 'Región de Los Lagos' },
          { label: 'Calbuco', value: 'Calbuco', region: 'Región de Los Lagos' },
          { label: 'Castro', value: 'Castro', region: 'Región de Los Lagos' },
          { label: 'Chaitén', value: 'Chaitén', region: 'Región de Los Lagos' },
          { label: 'Chonchi', value: 'Chonchi', region: 'Región de Los Lagos' },
          { label: 'Cochamó', value: 'Cochamó', region: 'Región de Los Lagos' },
          { label: 'Curaco de Vélez', value: 'Curaco de Vélez', region: 'Región de Los Lagos' },
          { label: 'Dalcahue', value: 'Dalcahue', region: 'Región de Los Lagos' },
          { label: 'Fresia', value: 'Fresia', region: 'Región de Los Lagos' },
          { label: 'Frutillar', value: 'Frutillar', region: 'Región de Los Lagos' },
          { label: 'Futaleufú', value: 'Futaleufú', region: 'Región de Los Lagos' },
          { label: 'Hualaihué', value: 'Hualaihué', region: 'Región de Los Lagos' },
          { label: 'Llanquihue', value: 'Llanquihue', region: 'Región de Los Lagos' },
            { label: 'Los Muermos', value: 'Los Muermos', region: 'Región de Los Lagos' },
            { label: 'Maullín', value: 'Maullín', region: 'Región de Los Lagos' },
            { label: 'Osorno', value: 'Osorno', region: 'Región de Los Lagos' },
            { label: 'Palena', value: 'Palena', region: 'Región de Los Lagos' },
            { label: 'Puerto Montt', value: 'Puerto Montt', region: 'Región de Los Lagos' },
            { label: 'Puerto Octay', value: 'Puerto Octay', region: 'Región de Los Lagos' },
            { label: 'Puerto Varas', value: 'Puerto Varas', region: 'Región de Los Lagos' },
            { label: 'Puqueldón', value: 'Puqueldón', region: 'Región de Los Lagos' },
          { label: 'Purranque', value: 'Purranque', region: 'Región de Los Lagos' },
          { label: 'Puyehue', value: 'Puyehue', region: 'Región de Los Lagos' },
          { label: 'Queilén', value: 'Queilén', region: 'Región de Los Lagos' },
          { label: 'Quellón', value: 'Quellón', region: 'Región de Los Lagos' },
          { label: 'Quemchi', value: 'Quemchi', region: 'Región de Los Lagos' },
          { label: 'Quinchao', value: 'Quinchao', region: 'Región de Los Lagos' },
          { label: 'Río Negro', value: 'Río Negro', region: 'Región de Los Lagos' },
          { label: 'San Juan de la Costa', value: 'San Juan de la Costa', region: 'Región de Los Lagos' },
          { label: 'San Pablo', value: 'San Pablo', region: 'Región de Los Lagos' },
        ]
      },
      {
        label: 'Región de Aysén del G. Carlos Ibáñez del Campo',
        options: [
          { label: 'Aysén', value: 'Aysén', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Chile Chico', value: 'Chile Chico', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Cisnes', value: 'Cisnes', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Cochrane', value: 'Cochrane', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Coyhaique', value: 'Coyhaique', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Guaitecas', value: 'Guaitecas', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Lago Verde', value: 'Lago Verde', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: "O'Higgins", value: "O'Higgins", region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Río Ibáñez', value: 'Río Ibáñez', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
          { label: 'Tortel', value: 'Tortel', region: 'Región de Aysén del G. Carlos Ibáñez del Campo' },
        ]
      },
      {
        label: 'Región de Magallanes y de la Antártica Chilena',
        options: [
          { label: 'Antártica', value: 'Antártica', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Cabo de Hornos', value: 'Cabo de Hornos', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Laguna Blanca', value: 'Laguna Blanca', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Natales', value: 'Natales', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Porvenir', value: 'Porvenir', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Primavera', value: 'Primavera', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Punta Arenas', value: 'Punta Arenas', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Río Verde', value: 'Río Verde', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'San Gregorio', value: 'San Gregorio', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Timaukel', value: 'Timaukel', region: 'Región de Magallanes y de la Antártica Chilena' },
          { label: 'Torres del Paine', value: 'Torres del Paine', region: 'Región de Magallanes y de la Antártica Chilena' },
        ]
      },
      {
        label: 'Región Metropolitana de Santiago',
        options: [
          { label: 'Alhué', value: 'Alhué', region: 'Región Metropolitana de Santiago' },
          { label: 'Buin', value: 'Buin', region: 'Región Metropolitana de Santiago' },
          { label: 'Calera de Tango', value: 'Calera de Tango', region: 'Región Metropolitana de Santiago' },
          { label: 'Cerrillos', value: 'Cerrillos', region: 'Región Metropolitana de Santiago' },
          { label: 'Cerro Navia', value: 'Cerro Navia', region: 'Región Metropolitana de Santiago' },
          { label: 'Colina', value: 'Colina', region: 'Región Metropolitana de Santiago' },
          { label: 'Conchalí', value: 'Conchalí', region: 'Región Metropolitana de Santiago' },
          { label: 'Curacaví', value: 'Curacaví', region: 'Región Metropolitana de Santiago' },
          { label: 'El Bosque', value: 'El Bosque', region: 'Región Metropolitana de Santiago' },
            { label: 'El Monte', value: 'El Monte', region: 'Región Metropolitana de Santiago' },
            { label: 'Estación Central', value: 'Estación Central', region: 'Región Metropolitana de Santiago' },
            { label: 'Huechuraba', value: 'Huechuraba', region: 'Región Metropolitana de Santiago' },
            { label: 'Independencia', value: 'Independencia', region: 'Región Metropolitana de Santiago' },
            { label: 'Isla de Maipo', value: 'Isla de Maipo', region: 'Región Metropolitana de Santiago' },
            { label: 'La Cisterna', value: 'La Cisterna', region: 'Región Metropolitana de Santiago' },
            { label: 'La Florida', value: 'La Florida', region: 'Región Metropolitana de Santiago' },
            { label: 'La Granja', value: 'La Granja', region: 'Región Metropolitana de Santiago' },
          { label: 'Lampa', value: 'Lampa', region: 'Región Metropolitana de Santiago' },
          { label: 'La Pintana', value: 'La Pintana', region: 'Región Metropolitana de Santiago' },
          { label: 'La Reina', value: 'La Reina', region: 'Región Metropolitana de Santiago' },
          { label: 'Las Condes', value: 'Las Condes', region: 'Región Metropolitana de Santiago' },
          { label: 'Lo Barnechea', value: 'Lo Barnechea', region: 'Región Metropolitana de Santiago' },
          { label: 'Lo Espejo', value: 'Lo Espejo', region: 'Región Metropolitana de Santiago' },
          { label: 'Lo Prado', value: 'Lo Prado', region: 'Región Metropolitana de Santiago' },
          { label: 'Macul', value: 'Macul', region: 'Región Metropolitana de Santiago' },
          { label: 'Maipú', value: 'Maipú', region: 'Región Metropolitana de Santiago' },
          { label: 'María Pinto', value: 'María Pinto', region: 'Región Metropolitana de Santiago' },
          { label: 'Melipilla', value: 'Melipilla', region: 'Región Metropolitana de Santiago' },
          { label: 'Ñuñoa', value: 'Ñuñoa', region: 'Región Metropolitana de Santiago' },
          { label: 'Padre Hurtado', value: 'Padre Hurtado', region: 'Región Metropolitana de Santiago' },
            { label: 'Paine', value: 'Paine', region: 'Región Metropolitana de Santiago' },
            { label: 'Pedro Aguirre Cerda', value: 'Pedro Aguirre Cerda', region: 'Región Metropolitana de Santiago' },
            { label: 'Peñaflor', value: 'Peñaflor', region: 'Región Metropolitana de Santiago' },
            { label: 'Peñalolén', value: 'Peñalolén', region: 'Región Metropolitana de Santiago' },
            { label: 'Pirque', value: 'Pirque', region: 'Región Metropolitana de Santiago' },
            { label: 'Providencia', value: 'Providencia', region: 'Región Metropolitana de Santiago' },
            { label: 'Pudahuel', value: 'Pudahuel', region: 'Región Metropolitana de Santiago' },
            { label: 'Puente Alto', value: 'Puente Alto', region: 'Región Metropolitana de Santiago' },
          { label: 'Quilicura', value: 'Quilicura', region: 'Región Metropolitana de Santiago' },
          { label: 'Quinta Normal', value: 'Quinta Normal', region: 'Región Metropolitana de Santiago' },
          { label: 'Recoleta', value: 'Recoleta', region: 'Región Metropolitana de Santiago' },
          { label: 'Renca', value: 'Renca', region: 'Región Metropolitana de Santiago' },
          { label: 'San Bernardo', value: 'San Bernardo', region: 'Región Metropolitana de Santiago' },
          { label: 'San Joaquín', value: 'San Joaquín', region: 'Región Metropolitana de Santiago' },
          { label: 'San José de Maipo', value: 'San José de Maipo', region: 'Región Metropolitana de Santiago' },
          { label: 'San Miguel', value: 'San Miguel', region: 'Región Metropolitana de Santiago' },
          { label: 'San Pedro', value: 'San Pedro', region: 'Región Metropolitana de Santiago' },
          { label: 'San Ramón', value: 'San Ramón', region: 'Región Metropolitana de Santiago' },
          { label: 'Santiago', value: 'Santiago', region: 'Región Metropolitana de Santiago' },
          { label: 'Talagante', value: 'Talagante', region: 'Región Metropolitana de Santiago' },
          { label: 'Tiltil', value: 'Tiltil', region: 'Región Metropolitana de Santiago' },
          { label: 'Vitacura', value: 'Vitacura', region: 'Región Metropolitana de Santiago' },
        ]
      },
      
  ];
export default comunas